import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import vm from 'node:vm';
const root=resolve(import.meta.dirname,'..'),read=path=>readFileSync(resolve(root,path),'utf8');
let checks=0;const check=(actual,expected)=>{assert.deepEqual(actual,expected);checks++;};
const context=vm.createContext({});vm.runInContext(read('public/assets/tracking-display.js'),context);
const display=context.TrackerDisplay,reading={id:1,title:'阅读',tracked:true,once_only:false};
check(display.bookTitle(reading,{completed:true,note:''}),'');
check(display.bookTitle(reading,{completed:true,note:' 《悉达多》 '}),'《悉达多》');
check(display.bookTitle({...reading,title:'阅读En'},{completed:true,note:'A Book'}),'A Book');
check(display.bookTitle(reading,{completed:false,note:'暂存书名'}),'');
check(display.bookTitle({...reading,title:'跑步'},{completed:true,note:'跑步备注'}),'');
check(display.bookTitle({...reading,once_only:true},{completed:true,note:'单次备注'}),'');
let record={completed:true,note:'《悉达多》',links:[]};
Object.assign(context,{today:'2026-10-09',dateFor:day=>`2026-10-${String(day).padStart(2,'0')}`,getRecord:()=>record,esc:display.escape,markHtml:()=>'<span>✓</span>'});
const source=read('public/assets/app.js');vm.runInContext(source.slice(source.indexOf('function cellHtml('),source.indexOf('function groupHtml(')),context);
let cell=context.cellHtml(reading,9);check(cell.includes('class="book-title">《悉达多》'),true);check(cell.includes('<span>✓</span>'),false);
record={completed:true,note:'<img src=x onerror="alert(1)">',links:[]};cell=context.cellHtml(reading,9);check(cell.includes('<img'),false);check(cell.includes('&lt;img'),true);
record={completed:true,note:'',links:[]};check(context.cellHtml(reading,9).includes('<span>✓</span>'),true);
record={completed:false,note:'暂存书名',links:[]};check(context.cellHtml(reading,9).includes('book-title'),false);check(context.cellHtml(reading,9).includes('cell-note'),true);
const manifest=JSON.parse(read('public/manifest.webmanifest'));check(manifest.display,'standalone');check(manifest.start_url,'./');check(manifest.id,'./');
for(const icon of manifest.icons){const bytes=readFileSync(resolve(root,'public',icon.src));check(`${bytes.readUInt32BE(16)}x${bytes.readUInt32BE(20)}`,icon.sizes);}
const handlers=new Map(),deleted=[],stored=[],cache={addAll:async urls=>stored.push(...urls),match:async()=>null,put:async request=>stored.push(request.url)};
const worker=vm.createContext({URL,Set,Response,fetch:async()=>new Response('private-user-data'),caches:{open:async()=>cache,keys:async()=>['month-tracker-static-%2F-0.6.0','other-app-cache'],delete:async key=>deleted.push(key)},self:{location:{href:'https://example.com/sw.js'},clients:{claim:async()=>{}},skipWaiting:async()=>{},addEventListener:(name,callback)=>handlers.set(name,callback)}});
vm.runInContext(read('public/sw.js'),worker);
let pending;handlers.get('install')({waitUntil:p=>pending=p});await pending;
check(stored.length,7);check(stored.some(u=>u.includes('api.php')||u.includes('index.php')),false);
handlers.get('activate')({waitUntil:p=>pending=p});await pending;check(deleted,['month-tracker-static-%2F-0.6.0']);
const count=stored.length;
const fetchEvent=async request=>{let response;handlers.get('fetch')({request,respondWith:p=>response=p});return response?await response:undefined;};
check(await fetchEvent({method:'GET',mode:'cors',url:'https://example.com/api.php?action=month'}),undefined);
check(await fetchEvent({method:'POST',mode:'cors',url:'https://example.com/api.php?action=records'}),undefined);
await fetchEvent({method:'GET',mode:'navigate',url:'https://example.com/'});check(stored.length,count);
worker.fetch=async()=>{throw new Error('offline');};const offline=await fetchEvent({method:'GET',mode:'navigate',url:'https://example.com/'});check(offline.status,503);check((await offline.text()).includes('private-user-data'),false);check(offline.headers.get('Cache-Control'),'no-store');
// Exercise install readiness, user-driven prompt, cancellation and installed state.
const elements=new Map(['install-dialog','install-confirm','install-status','install-close','mobile-menu'].map(id=>[id,{hidden:false,disabled:false,open:false,showModal(){this.open=true;},close(){this.open=false;}}]));
const entry={hidden:false},installHandlers=new Map(),standalone={matches:false,addEventListener(){}},registrations=[];
const installContext=vm.createContext({document:{getElementById:id=>elements.get(id),querySelectorAll:()=>[entry]},window:{isSecureContext:true,matchMedia:()=>standalone,addEventListener:(name,fn)=>installHandlers.set(name,fn)},navigator:{serviceWorker:{register:async(...args)=>registrations.push(args)}}});
vm.runInContext(read('public/assets/pwa.js'),installContext);check(elements.get('install-confirm').hidden,true);check(registrations[0][0],'sw.js');
let prompts=0,prevented=false;installHandlers.get('beforeinstallprompt')({preventDefault(){prevented=true;},prompt:async()=>{prompts++;},userChoice:Promise.resolve({outcome:'dismissed'})});check(prevented,true);check(prompts,0);check(elements.get('install-confirm').hidden,false);
entry.onclick();check(elements.get('install-dialog').open,true);check(prompts,0);await elements.get('install-confirm').onclick();check(prompts,1);check(elements.get('install-confirm').hidden,true);check(elements.get('install-status').textContent.includes('已取消'),true);
installHandlers.get('appinstalled')();check(entry.hidden,true);
console.log(`PASS: ${checks} reading display, manifest, install UI and private-cache assertions.`);
